### ISSUE TITLE
Wolfpack RPG unresponsive command

### ISSUE THREAD

**Issue by yencim** [EmpyrealHell/wolfpack-rpg-client#15] opened 2020-03-20 20:51 UTC
Entering input doesn't receive an output for most commands e.g. !queue. This may be a feature and it acts in the background however, I'm not sure.

Also I noticed that selecting a class doesn't work, to confirm whether or not I had selected one in the past I requested a respec but alas nothing came of it.

I have been looking forward to playing this rpg so I hope it is solved soon, no pressure. Thank you!

**Comment by EmpyrealHell** [comment] 2020-03-20 23:18
I need some more information from you before I can look into this, as I cannot reproduce this issue.

1. What browser and version are you using?
2. What platform are you using (desktop/ios/android/etc)?
3. Are you able to send and receive whispers from lobot through the twitch app/website?
4. What version number do you see at the top of the client?
5. Is your browser's websocket connection working properly? To check: 
    1. Enter the dev console by pressing f12
    2. Click on the network tab
    3. Refresh the app
    4. Find the irc-ws.chat.twitch.tv entry, it should have a status of 101
    5. When you send a message through the console, it should show up in the data column with a green up arrow
    6. The value of the entry that appears right after it should be lobot's response

**Comment by yencim** [comment] 2020-03-23 22:50
Hi EmpyrealHell,

Thank you for getting back to me and sorry for responding so late.
I am using Opera GX on desktop.

I am able to whisper to Lobot but he doesn't respond to anything but !stats.

Client version 67.0.3575.87

When using in the network tab, I can see lobot's response to stats but when using something like queue or C1 to select a class, it recognises C1 or queue as an input but there is no mention of an output. 

There is however a persisted query called: version: 1     sha265Hash.

**Comment by EmpyrealHell** [comment] 2020-03-23 23:36
If lobot isn't responding to you through twitch, then I'm afraid that's not an issue with the website. There may be some issue with your account on the bot, where it isn't recognizing your level. Try one of the other commands not tied to your level, like the help command (literally just whisper the word help to lobotjr). If that works too then it's an issue between you and the bot, and I can only really help if it's an issue with the web client.

As long as you're at least level 3, you should be able to select your class and queue for the dungeon finder. If the !stats response shows you at level 3 or above and it still doesn't work, let lobosjr know in chat and he may be able to fix it.

**Comment by yencim** [comment] 2020-03-24 00:02
Thank you,

Ok so I believe I found the issue, I found the service worker wasn't running for twitch and now he responds to help messages (which previously didn't cause a response), however I have to close the whisper and open a new one to trigger that response.

Ok bit of an update, nothing but help and stats works so yeah it might be up to lobos to sort it. Don't know for sure though.

**Comment by EmpyrealHell** [comment] 2020-03-24 22:11
Having to close and reopen the whisper window or refresh the page is a bug with twitch's whisper system. Getting around that issue was actually the primary reason we created this web client. I'm going to close this bug for now though, as it seems like it's an issue with the bot itself rather than the client. If you get it working through the twitch app or their website but it still isn't working in the web client, let me know and I'll reopen this and look into it.

**Closed by EmpyrealHell** 2020-03-24 22:11 UTC
